name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    container:
      image: python:3.11
      
    steps:
      - name: checkout
      - uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-python@v4
        with: python-version: '3.11'

      - name: install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute
        env:
          SOME_SECRET: AAA
        run: python main.py
